# Todo Using range function in loop
"""
    The range() is an in-built function in Python.
    It returns a sequence of numbers starting from zero and increment by 1
    by default and stops before the given number.

    sequence numbers generated by range will not be saved in memory,
    but we can use them for any operation.

    range will generate numbers from starting point & ending point
"""
# Todo print numbers from 10 to 100 with out loop
# Todo range (start, end)
print("Range Numbers: " + str(range(10, 100)))
"""
    Above method is generating numbers 
    but not showing so we need to type cast it in list
    ending number is exclusive
"""
print("Range Numbers: " + str(list(range(10, 100))))

# Todo generate numbers from 0 to 10
print("Numbers 0 to 10 %s" % str(list(range(10))))

# Todo generate even numbers from 0 to 100
print("Even Numbers 0 to 100 %s" % str(list(range(0, 100, 2))))

# Todo generate odd numbers from 0 to 100 by range
print("*"*100)
print("Odd Numbers")
# my_list = list(range(100))
for n in range(100):
    if n % 2 == 0:
        continue
    print(n, end=", ")
